#Exercícios Numpy

Fonte: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb

1 - Importe a biblioteca numpy com o alias "np"

In [ ]:
import numpy as np

2 - Crie um array qualquer e informe o tamanho deste vetor em memória.

In [ ]:
z = np.zeros((10,10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


3 - Reduza o tamanho do array anterior em memória sem alterar ou excluir nenhum dado e exiba o novo tamanho do array.

In [ ]:
z = np.int16(z)
print("%d bytes" % (z.size * z.itemsize))

200 bytes


4 - Crie um vetor com valores de 10 a 49

In [ ]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


5 - Inverta o vetor anterior

In [ ]:
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


6- Crie uma matriz 3x3 com valores que variam de 0 a 8

In [ ]:
z = np.arange(9).reshape(3, 3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7- Encontre índices de elementos diferentes de zero de [1,2,0,0,4,0] (dica: tem função pronta para isso)

In [ ]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


8 - Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo, máximo, média, moda e desvio padrão.

In [ ]:
z = np.random.random((10,10))


print("máximo", z.max())
print("mínimo", z.min())
print("média", z.mean())
print("mediana", np.quantile(z, 0.5))
print("desvio padrão", z.std())


máximo 0.9929273709594368
mínimo 0.010136167653766903
média 0.5274681482737898
moda 0.5406014497338846
desvio padrão 0.2796829789918641


In [ ]:
np.random.seed(122)
z = np.random.randint(0, 2, size=(2,2))
print(z)

unique, counts = np.unique(z, return_counts=True)

moda = unique[np.where(counts==counts.max())]
moda

[[1 0]
 [0 0]]


array([0])

9 - Dada uma matriz 1D, multiplique por 10 todos os elementos que estão entre 3 e 8.

In [ ]:
z = np.arange(11)
z[(3 < z) & (z < 8)] *= 10
print(z)

[ 0  1  2  3 40 50 60 70  8  9 10]


10 - Crie uma matriz 5x5 com valores de linha variando de 0 a 4

In [ ]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


11 - Crie um vetor de inteiros aleatórios de tamanho 10 e ordene-o

In [ ]:
np.random.seed(0)
z = np.random.randint(0,5, size=(10))
print(z)
z.sort()
print(z)

[4 0 3 3 3 1 3 2 4 0]
[0 0 1 2 3 3 3 3 4 4]


12 - Crie o mesmo vetor da questão anterior (com o mesmo seed) e exiba a ordem de seus índices (função argsort)

In [ ]:
np.random.seed(0)
z = np.random.randint(0,5, size=(10))
print(z)

print(z.argsort())

[4 0 3 3 3 1 3 2 4 0]
[1 9 5 7 2 3 4 6 0 8]


13 - Crie um vetor aleatório de tamanho 10 e substitua o valor máximo por 0

In [ ]:
z = np.random.random(10)
print(z)
z[z.argmax()] = 0
print(z)

[0.3927848  0.83607876 0.33739616 0.64817187 0.36824154 0.95715516
 0.14035078 0.87008726 0.47360805 0.80091075]
[0.3927848  0.83607876 0.33739616 0.64817187 0.36824154 0.
 0.14035078 0.87008726 0.47360805 0.80091075]


14 - Crie uma matriz 3x3 e exiba o índice e o valor de cada posição. (dica: consulte as funções np.ndenumerate e np.ndindex)

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)

print("\n\n")
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8



(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


15- Como ordenar uma matriz pela coluna do meio?

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,2].argsort()])

[[7 1 8]
 [0 0 5]
 [8 6 8]]
[[0 0 5]
 [7 1 8]
 [8 6 8]]
